services:
  hyperbole:
    build: .
    container_name: hyperbole-web
    expose:
      - "8080"
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: http://hyperbole.namanvashistha.com
      caddy.reverse_proxy: "{{upstreams 8080}}"

networks:
  caddy:
    external: true
